# Generated by Django 4.1.7 on 2023-04-02 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='delivery_address')),
                ('promocode', models.CharField(blank=True, max_length=20, verbose_name='promocode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('products', models.ManyToManyField(related_name='orders', to='shop.product', verbose_name='products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
