# Generated by Django 4.1.7 on 2023-04-03 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('opening', models.TimeField(blank=True, verbose_name='opening')),
                ('closing', models.TimeField(blank=True, verbose_name='closing')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start', models.TimeField(blank=True, verbose_name='start')),
                ('end', models.TimeField(blank=True, verbose_name='end')),
                ('products', models.ManyToManyField(blank=True, related_name='products', to='shop.product', verbose_name='products')),
                ('users', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
            },
        ),
    ]
