# Generated by Django 4.1.7 on 2023-04-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='closing',
            field=models.TimeField(verbose_name='closing'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening',
            field=models.TimeField(verbose_name='opening'),
        ),
    ]
