# Generated by Django 4.1.7 on 2023-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shop_closing_alter_shop_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end',
            field=models.TimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start',
            field=models.TimeField(verbose_name='start'),
        ),
    ]
