# Generated by Django 4.1.7 on 2023-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_promotion_end_alter_promotion_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end',
            field=models.DateField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start',
            field=models.DateField(verbose_name='start'),
        ),
    ]
