# Generated by Django 4.1.7 on 2023-04-03 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_alter_promotion_end_alter_promotion_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(default=None, null=True, related_name='products', to='shop.product', verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='users',
            field=models.ManyToManyField(default=None, null=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
